// SPDX-License-Identifier: AGPL-3.0-only
import type { Field, Workbench } from "./tool-types";

const program = `#include <stdio.h>

int main(void) {
    for (int i = 1; i <= 5; ++i) {
        printf("%d squared = %d\\n", i, i * i);
    }
    return 0;
}
`;
const standard: Field = {
  key: "standard",
  label: "Language standard",
  choices: ["c99", "c11", "c17", "c++11", "c++14", "c++17"],
  value: "c++17",
};
const optimization: Field = {
  key: "optimization",
  label: "Optimization",
  choices: ["0", "1", "2", "3", "s", "z"],
  value: "0",
};
const compilerHelp =
  "Experimental Clang/LLD 8.0.1, running locally with bundled C/C++ headers and libraries. Single source file; C99–C17 and C++11–C++17. No filesystem access, external libraries, OS threads, or exception handling. Exported programs use legacy wasi_unstable imports. Assets load on demand (about 57 MiB for compile/run). Limits: 1 MiB source and stdin, 60 seconds, 256 MiB program memory, 256 KiB per output stream.";
function tool(
  id: string,
  name: string,
  description: string,
  sample: string,
  fields: Field[] = [],
  extra: Partial<Workbench> = {},
): Workbench {
  return {
    id: `cpp-${id}`,
    name,
    description,
    sample,
    fields,
    group: "Developer",
    tags: ["c", "cpp", "developer", "wasm"],
    keywords: ["c++", "clang", "gcc", "toolchain"],
    option: "",
    optionLabel: "",
    inputMode: "optional-file",
    accept: ".c,.cc,.cpp,.cxx,.h,.hpp,.txt,text/plain",
    ...extra,
  };
}
export const cppTools: Workbench[] = [
  tool(
    "runner",
    "C/C++ compiler & runner",
    "Compile C or C++ to WebAssembly, run it with stdin, and save the compiled program.",
    program,
    [
      standard,
      optimization,
      {
        key: "action",
        label: "Action",
        choices: ["Compile and run", "Compile only"],
        value: "Compile and run",
      },
      { key: "stdin", label: "Standard input", type: "textarea", value: "" },
    ],
    {
      tags: ["c", "cpp", "developer", "wasm", "compilers"],
      help: compilerHelp,
    },
  ),
  tool(
    "check",
    "C/C++ syntax & type checker",
    "Use Clang to check source types, syntax, and warnings without running it.",
    program,
    [standard],
    { help: compilerHelp },
  ),
  tool(
    "preprocess",
    "C/C++ preprocessor",
    "Expand macros, conditionals, and bundled includes using Clang.",
    "#define SQUARE(x) ((x) * (x))\nint answer = SQUARE(7);\n",
    [standard],
    { help: compilerHelp + " Preprocessed output is limited to 1 MiB." },
  ),
  tool(
    "assembly",
    "C/C++ to WebAssembly assembly",
    "Inspect the WebAssembly assembly generated by Clang at different optimization levels.",
    "int square(int x) { return x * x; }\n",
    [standard, optimization],
    { help: compilerHelp + " Assembly output is limited to 1 MiB." },
  ),
  tool(
    "format",
    "C/C++ formatter",
    "Format source with clang-format presets or your own .clang-format configuration.",
    program,
    [
      {
        key: "language",
        label: "Language",
        choices: ["C++", "C"],
        value: "C++",
      },
      {
        key: "style",
        label: "Style",
        choices: [
          "LLVM",
          "Google",
          "Chromium",
          "Mozilla",
          "WebKit",
          "Microsoft",
          "GNU",
          "Custom",
        ],
        value: "LLVM",
      },
      {
        key: "customStyle",
        label: "Custom .clang-format (when Custom is selected)",
        type: "textarea",
        value: "BasedOnStyle: LLVM\nIndentWidth: 4\nColumnLimit: 100",
      },
    ],
    {
      tags: ["c", "cpp", "developer", "formatting", "wasm"],
      help: "clang-format 23.1.0 loads on first use. Runs locally in a stoppable worker. Source limit: 1 MiB.",
    },
  ),
  tool(
    "demangle",
    "C++ symbol demangler",
    "Decode GCC/Clang Itanium and Microsoft C++ mangled names.",
    "_ZN3foo3barEi\n?func@@YAHH@Z\n",
    [],
    {
      help: "One symbol per line. Supports Itanium and MSVC encodings; undecodable symbols remain visible. Up to 2,000 symbols, 8 KiB each.",
    },
  ),
  tool(
    "compilation-db",
    "Compilation database inspector",
    "Explore compile_commands.json entries, include paths, defines, standards, and build variants.",
    JSON.stringify(
      [
        {
          directory: "/project/build",
          file: "../src/main.cpp",
          arguments: [
            "clang++",
            "-std=c++17",
            "-I../include",
            "-DDEBUG=1",
            "-c",
            "../src/main.cpp",
            "-o",
            "main.o",
          ],
        },
      ],
      null,
      2,
    ),
    [],
    {
      accept: ".json,application/json",
      tags: ["c", "cpp", "developer", "json", "build"],
      help: "Inspects up to 10,000 entries / 2 MiB. Extracts common flags from arguments arrays; command strings and response-file references are preserved without shell parsing, fetching, or execution.",
    },
  ),
  tool(
    "cmake-cache",
    "CMake cache inspector",
    "Read typed cache entries and their descriptions, with optional internal variables.",
    "//Choose the build type\nCMAKE_BUILD_TYPE:STRING=Release\n//Build shared libraries\nBUILD_SHARED_LIBS:BOOL=ON\nCMAKE_CACHE_MAJOR_VERSION:INTERNAL=4\n",
    [
      {
        key: "internal",
        label: "Include internal and static entries",
        type: "checkbox",
        value: "false",
      },
    ],
    {
      accept: ".txt,.cache,text/plain",
      tags: ["c", "cpp", "developer", "cmake", "build"],
      help: "Reads CMakeCache.txt without evaluating CMake code. Values remain strings. Limit: 2 MiB / 10,000 displayed entries.",
    },
  ),
  tool(
    "diagnostics",
    "C/C++ diagnostic log reader",
    "Turn GCC, Clang, and MSVC file diagnostics into a structured, copyable table.",
    "src/main.cpp:8:5: warning: unused variable 'n' [-Wunused-variable]\n    int n = 42;\n        ^\nC:\\project\\main.cpp(12,3): error C2065: 'missing': undeclared identifier\n",
    [],
    {
      accept: ".log,.txt,text/plain",
      tags: ["c", "cpp", "developer", "errors", "logs"],
      help: "Reads existing file:line or file(line,column) diagnostics, including up to eight context lines each. Limit: 2 MiB / 10,000 diagnostics.",
    },
  ),
  tool(
    "byte-array",
    "File to C/C++ byte array",
    "Embed file bytes or UTF-8 text as a C array or a constexpr C++ std::array.",
    "Hello, world!\n",
    [
      { key: "name", label: "Variable name", value: "payload" },
      {
        key: "language",
        label: "Output language",
        choices: ["C", "C++"],
        value: "C",
      },
      {
        key: "uppercase",
        label: "Uppercase hex digits",
        type: "checkbox",
        value: "false",
      },
      {
        key: "terminator",
        label: "Append a null byte",
        type: "checkbox",
        value: "false",
      },
    ],
    {
      accept: "",
      tags: ["c", "cpp", "developer", "files", "converters", "hex"],
      help: "Up to 64 KiB. Preserves every byte and emits an explicit length. An empty C array uses a storage sentinel with logical length zero.",
    },
  ),
];
export const cppIds = new Set(cppTools.map((tool) => tool.id));
export const cppRuntimeIds = new Set([
  "cpp-runner",
  "cpp-check",
  "cpp-preprocess",
  "cpp-assembly",
  "cpp-format",
]);
