// SPDX-License-Identifier: AGPL-3.0-only
import type { Tool } from "./tool-types";

const tool = (
  id: string,
  name: string,
  description: string,
  sample: string,
  option = "",
  optionLabel = "",
  tags: string[] = [],
): Tool => ({
  id,
  name,
  description,
  sample,
  option,
  optionLabel,
  group: "Developer",
  tags: ["developer", ...tags],
});

export const developerTools: Tool[] = [
  tool(
    "json-typescript",
    "JSON → TypeScript",
    "Infer a TypeScript type from example JSON, merging object shapes in arrays. This describes the sample, not an API contract.",
    '[{"id":1,"name":"Ada"},{"id":2,"name":"Lin","active":true}]',
    "Root",
    "Type name",
    ["json", "typescript", "code", "converters"],
  ),
  tool(
    "json-schema",
    "JSON Schema validator",
    "Validate JSON against a JSON Schema. Local references work; remote references are not fetched. Shows up to 100 errors.",
    '{"name":"Ada","age":"twenty"}',
    '{"type":"object","required":["name","age"],"properties":{"name":{"type":"string"},"age":{"type":"integer","minimum":0}},"additionalProperties":false}',
    "JSON Schema",
    ["json", "validation", "data"],
  ),
  tool(
    "json-diff",
    "Structural JSON diff",
    "Compare JSON values by path. Ignores object key order; array positions are significant.",
    '{"name":"Ada","roles":["reader"],"active":true}',
    '{"name":"Ada","roles":["reader","writer"],"active":false}',
    "Updated JSON",
    ["json", "diff", "data"],
  ),
  tool(
    "curl-fetch",
    "cURL → fetch",
    "Convert a supported single-request curl command to JavaScript. Does not send requests. Supports -X, -H, -d, --data-raw, --data-binary and --url.",
    "curl https://example.com/api -X POST -H 'Content-Type: application/json' --data-raw '{\"name\":\"Ada\"}'",
    "",
    "",
    ["http", "code", "converters"],
  ),
  tool(
    "regex-playground",
    "Regex playground",
    "Highlight matches and inspect capture groups. Rust regex syntax: use inline flags like (?i). No lookaround or backreferences; up to 1,000 matches.",
    "Ada: 42\nLin: 87",
    "(?P<name>\\w+): (?P<score>\\d+)",
    "Regular expression",
    ["regex", "text", "validation"],
  ),
  tool(
    "cron-explorer",
    "Cron schedule explorer",
    "List the next 10 runs after a date. Accepts 5 fields or seconds + 5 fields; optional year. Day-of-month and day-of-week both constrain matching.",
    "*/15 9-17 * * MON-FRI",
    "2026-09-14T08:00:00+08:00",
    "Start date with UTC offset",
    ["cron", "dates"],
  ),
  tool(
    "env-diff",
    ".env comparison",
    "Compare literal single-line KEY=value settings. Supports export and simple quotes; does not expand variables or shell expressions.",
    "PORT=3000\nLOG_LEVEL=info\nOLD_FLAG=1",
    "PORT=8080\nLOG_LEVEL=info\nNEW_FLAG=1",
    "Updated .env",
    ["configuration", "diff", "text"],
  ),
  tool(
    "semver-test",
    "Semver range tester",
    "Test Cargo-style version requirements: caret, tilde, wildcards, and comma-separated comparisons. npm || and hyphen ranges are not supported.",
    "1.2.3\n1.9.0\n2.0.0\n1.3.0-beta.1",
    "^1.2.0",
    "Version requirement",
    ["versions", "validation"],
  ),
  tool(
    "hex-viewer",
    "Hex viewer",
    "Inspect a local file as offset, hex bytes and ASCII. Preview shows the first 64 KiB; maximum file size 1 MiB.",
    "SGVsbG8gV29ybGQh",
    "",
    "",
    ["files", "binary"],
  ),
  tool(
    "csp-inspector",
    "CSP inspector",
    "Parse Content-Security-Policy directives and highlight duplicates and broad sources. Structural inspection, not a complete security assessment.",
    "default-src 'self'; script-src 'self' 'unsafe-inline'; img-src * data:; object-src 'none'",
    "",
    "",
    ["http", "security", "validation"],
  ),
];
