// SPDX-License-Identifier: AGPL-3.0-only
import type { Field, Workbench } from "./tool-types";

const field = (
  key: string,
  label: string,
  value: string,
  type?: Field["type"],
): Field => ({ key, label, value, type });
function tool(
  id: string,
  name: string,
  description: string,
  tags: string[],
  sample: string,
  fields: Field[],
  help: string,
  extra: Partial<Workbench> = {},
): Workbench {
  return {
    id: `everyday-${id}`,
    name,
    description,
    tags: [...new Set(["everyday", ...tags])],
    sample,
    fields,
    help,
    group: "Everyday",
    option: "",
    optionLabel: "",
    inputMode: "optional-file",
    accept: ".txt,.csv,text/plain,text/csv",
    ...extra,
  };
}
export const everydayTools: Workbench[] = [
  tool(
    "recipe",
    "Recipe scaler",
    "Scale ingredient quantities to a different number of servings.",
    ["cooking", "numbers", "planning"],
    "ingredient,quantity,unit\nFlour,250,g\nMilk,300,ml\nSalt,1/2,tsp",
    [
      field("original", "Original servings", "4", "number"),
      field("desired", "Desired servings", "6", "number"),
    ],
    "Enter CSV with ingredient,quantity,unit columns. Quantities accept decimals or fractions such as 1/2. Units stay unchanged; cooking times are not scaled.",
  ),
  tool(
    "bill",
    "Bill & tip splitter",
    "Split a bill equally while keeping every cent accounted for.",
    ["everyday", "numbers", "planning"],
    "Alex\nSam\nJo",
    [
      field("amount", "Subtotal", "120.00"),
      field("tax", "Tax amount", "0.00"),
      field("tip", "Tip percentage (before tax)", "10.00"),
    ],
    "One participant per line. Amounts use two decimal places in the same currency. Tip is rounded to the nearest cent; leftover cents go to the first participants.",
  ),
  tool(
    "unit-price",
    "Unit-price comparison",
    "Compare package prices per unit and rank the least expensive first.",
    ["shopping", "comparison", "numbers"],
    "item,price,quantity\nSmall pack,3.20,250\nLarge pack,5.50,500\nBulk pack,12.00,1000",
    [],
    "CSV columns: item,price,quantity. Use the same currency and quantity unit for every row (for example, grams).",
  ),
  tool(
    "print",
    "Print size & DPI calculator",
    "Calculate the pixel dimensions needed for a physical print size.",
    ["printing", "images", "numbers"],
    "",
    [
      field("width", "Width", "210", "number"),
      field("height", "Height", "297", "number"),
      {
        key: "unit",
        label: "Unit",
        choices: ["mm", "cm", "inches"],
        value: "mm",
      },
      field("dpi", "Pixels per inch", "300", "number"),
    ],
    "Rounds pixel dimensions up. Uncompressed RGB size assumes three bytes per pixel, excluding file headers and compression.",
    { inputMode: "none" },
  ),
  tool(
    "reading-time",
    "Reading & speaking time",
    "Estimate how long a passage takes to read or speak at your chosen pace.",
    ["writing", "text", "planning"],
    "Paste your article, script, speech, or presentation notes here to estimate the time needed to read it.",
    [
      field("reading", "Reading words per minute", "220", "number"),
      field("speaking", "Speaking words per minute", "130", "number"),
    ],
    "Estimates use Unicode word boundaries and your supplied pace; pauses and delivery style are not included.",
  ),
  tool(
    "business-days",
    "Business-day counter",
    "Count weekdays between dates while excluding your holiday list.",
    ["dates", "calendar", "planning"],
    "2026-01-01",
    [
      field("start", "Start date (YYYY-MM-DD)", "2026-01-01"),
      field("end", "End date (YYYY-MM-DD)", "2026-01-31"),
      field("inclusive", "Include end date", "true", "checkbox"),
    ],
    "Start is included. Weekends are Saturday and Sunday. Enter excluded dates one per line; no regional holidays are added automatically. Up to 100 years.",
  ),
  tool(
    "timesheet",
    "Timesheet calculator",
    "Total worked hours from shifts, including breaks and overnight work.",
    ["time", "planning", "csv"],
    "date,start,end,break_minutes\n2026-09-14,09:00,17:30,30\n2026-09-15,22:00,06:00,45",
    [],
    "CSV columns: date,start,end,break_minutes. Use 24-hour HH:MM. An earlier end time means the following day; equal times mean zero hours. Calculates wall-clock time without time zones or daylight-saving changes.",
  ),
  tool(
    "decision",
    "Weighted decision matrix",
    "Rank options using your criteria, scores, and relative weights.",
    ["planning", "comparison", "csv"],
    "option,Cost,Convenience,Quality\nOption A,8,6,7\nOption B,5,9,9\nOption C,9,5,6",
    [field("weights", "Criterion weights (in column order)", "3,2,5")],
    "First CSV column names each option; remaining columns are scores from 0 to 10, where higher is better. Provide one nonnegative weight per criterion. Weights are normalized automatically.",
  ),
  tool(
    "calendar",
    "Calendar event file",
    "Create an .ics event file to import into your calendar app.",
    ["calendar", "planning", "files"],
    "Discuss the project and agree on next steps.",
    [
      field("title", "Event title", "Team catch-up"),
      field("start", "Start in UTC (YYYY-MM-DDTHH:MM)", "2026-10-01T09:00"),
      field("end", "End in UTC (YYYY-MM-DDTHH:MM)", "2026-10-01T10:00"),
      field("location", "Location", "Online"),
    ],
    "The input is the event description. Times are explicitly UTC; your calendar displays them in its local time zone. Creates a file without sending invitations.",
    { accept: ".txt,text/plain" },
  ),
  tool(
    "csv-transpose",
    "CSV transpose",
    "Swap the rows and columns of a CSV file without losing quoted values.",
    ["csv", "data", "converters"],
    "Metric,Monday,Tuesday\nVisits,120,145\nOrders,12,18",
    [],
    "All rows must have the same number of columns. The first row is transposed as data. Up to 1,000 rows and 100 columns.",
  ),
  tool(
    "checklist",
    "Checklist progress",
    "Summarize completed and remaining tasks from a Markdown checklist.",
    ["markdown", "planning", "text"],
    "# Packing\n- [x] Passport\n- [ ] Charger\n- [ ] Tickets\n# Before leaving\n- [x] Water plants",
    [],
    "Reads - [ ], - [x], and - [X] tasks (also * and + bullets), with the latest heading as the section. Fenced code examples are ignored. Up to 10,000 tasks.",
    { accept: ".md,.txt,text/plain,text/markdown" },
  ),
  tool(
    "text-wrap",
    "Text line wrapper",
    "Wrap prose to a chosen line width while preserving existing line breaks.",
    ["text", "writing", "formatting"],
    "This is a longer paragraph that can be wrapped into shorter lines for plain-text email, notes, or documents. Existing paragraphs remain separate.",
    [field("width", "Characters per line", "60", "number")],
    "Counts Unicode grapheme clusters, preserves existing line breaks, and collapses whitespace within each line. Long words stay intact. Width is a character count, not a visual or terminal-cell measurement.",
  ),
];
export const everydayIds = new Set(everydayTools.map((tool) => tool.id));
