// SPDX-License-Identifier: AGPL-3.0-only
import { mkdir, writeFile } from "node:fs/promises";
import { contentSecurityPolicy, securityHeaders } from "../src/lib/security";

await mkdir("public/fingerprint", { recursive: true });
const collectorPolicy = contentSecurityPolicy(false, true);
await writeFile(
  "public/fingerprint/index.html",
  `<!doctype html>
<!-- SPDX-License-Identifier: AGPL-3.0-only -->
<html lang="en"><head><meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="${collectorPolicy}">
<meta name="referrer" content="no-referrer"><title>Local fingerprint collector</title>
</head><body><script type="module" src="./frame.js"></script></body></html>
`,
);
const headerLines = Object.entries(securityHeaders)
  .map(([name, value]) => `  ${name}: ${value}`)
  .join("\n");
const pagePolicy = contentSecurityPolicy();
await writeFile(
  "public/_headers",
  `# Generated by bun run build:security. Cloudflare Workers Static Assets response headers.
/*
${headerLines}
/
  Content-Security-Policy: ${pagePolicy}; frame-ancestors 'self'
/index.html
  Content-Security-Policy: ${pagePolicy}; frame-ancestors 'self'
/fingerprint
  Content-Security-Policy: ${collectorPolicy}; frame-ancestors 'self'
/fingerprint/*
  Content-Security-Policy: ${collectorPolicy}; frame-ancestors 'self'
`,
);
console.log("Generated deployment headers and isolated collector policy.");
